server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_SECRET:testeChaveJwt}
spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
